version: '3.7'
services:
  app:
    environment:
      - DB_HOST=postgres_db
      - REDIS_HOST=redis
    build:
      context: .
    container_name: 'dictionary_ms'
    depends_on:
      - postgres_db
      - redis
    ports:
      - "9100:9100"
    volumes:
      - ${VOLUME_STATIC}:/linguisage/static
#      if u haven't ssl cert just remove this line
       #/etc/letsencrypt:/linguisage/letsencrypt
      # - ${VOLUME_CERT}:/linguisage/letsencrypt

  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "9102:5432"
    volumes:
      - ${VOLUME_POSTGRES}:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4

  celery:
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgres_db
    build:
      context: .
    command: "celery -A background_tasks.celery:celery worker --loglevel=INFO -n dictionary -Q dictionary_queue"
    depends_on:
      - redis
    volumes:
      - ${VOLUME_STATIC}:/linguisage/static

  flower:
    environment:
      - REDIS_HOST=redis
      - DB_HOST=postgres_db
    build:
      context: .
    command: "celery -A background_tasks.celery:celery flower"
    ports:
      - "9105:5555"
