"""initial commit

Revision ID: 37ecbdb4833a
Revises: 
Create Date: 2024-02-15 15:47:07.072206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37ecbdb4833a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word",
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("sound_uk", sa.String(), nullable=True),
        sa.Column("sound_us", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alias",
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alias_alias"), "alias", ["alias"], unique=True)
    op.create_table(
        "sense",
        sa.Column(
            "lvl",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", native_enum=False),
            nullable=True,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("definition", sa.String(), nullable=False),
        sa.Column("short_cut", sa.String(), nullable=True),
        sa.Column("part_of_speech", sa.String(), nullable=True),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wordimage",
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["word.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "example",
        sa.Column("example", sa.String(), nullable=False),
        sa.Column("html_example", sa.String(), nullable=True),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sense_id"],
            ["sense.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "senseimage",
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sense_id"],
            ["sense.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("senseimage")
    op.drop_table("example")
    op.drop_table("wordimage")
    op.drop_table("sense")
    op.drop_index(op.f("ix_alias_alias"), table_name="alias")
    op.drop_table("alias")
    op.drop_table("word")
    # ### end Alembic commands ###
